# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- test
- Report generate
- Format checks
- Package deploy

# Pub deploy:
#   stage: Package deploy
#   image: ghcr.io/cirruslabs/flutter:$LATEST_FLUTTER_VERSION
#   tags:
#     - ubuntu
#   rules:
#     - if: '$CI_COMMIT_BRANCH =~ /^[0-9]+\.[0-9]+\/dart$/'
#     - if: '$CI_COMMIT_BRANCH == "latest/dart"'
#   before_script:
#     - dart pub get
#     - dart pub token add https://dart-packages.example.com --env-var $CI_JOB_TOKEN
#   script:
#     - dart pub publish --server=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/dart

Nuget deploy:
  stage: Package deploy
  image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2022
  tags:
    - windows
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^[0-9]+\.[0-9]+\/csharp$/'
    - if: '$CI_COMMIT_BRANCH == "latest/csharp"'
  before_script: iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) }"
  script: dotnet pack src/Dimerce.MavisClient/Dimerce.MavisClient.csproj -c Release;
          dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name $CI_COMMIT_BRANCH --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text;
          dotnet nuget push "src\Dimerce.MavisClient\bin\Release\*.nupkg" --source $CI_COMMIT_BRANCH;

Dart format check:
  stage: Format checks
  image: ghcr.io/cirruslabs/flutter:$LATEST_FLUTTER_VERSION
  tags:
    - ubuntu
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^[0-9]+\.[0-9]+\/dart$/'
    - if: '$CI_COMMIT_BRANCH == "latest/dart"'
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^[0-9]+\.[0-9]+\/dart$/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ "latest/dart"
  script:
    - dart format -l 100 --set-exit-if-changed .

sast:
  stage: test
  tags:
    - ubuntu
  artifacts:
    paths:
      - "gl-sast-report.json"
    expire_in: 1 days

sast_wiki_deploy:
  stage: Report generate
  tags:
    - ubuntu
  image: python:3.9
  before_script:
    - git clone --depth 1 --branch release/shallow https://gitlab-ci-token:${CI_JOB_TOKEN}@sources.didata.eu/dimerce/sast-wiki-dashboard.git
    - pip install python-gitlab
  script:
    - python sast-wiki-dashboard/deploy_wiki_sast_report.py

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
