# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2022

stages:
- test
- deploy

deploy:
  stage: deploy
  tags:
    - windows
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^[0-9]+\.[0-9]+\/csharp$/'
    - if: '$CI_COMMIT_BRANCH == "latest/csharp"'
  before_script: iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) }"
  script: dotnet pack src/Dimerce.MavisClient/Dimerce.MavisClient.csproj -c Release;
          dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name $CI_COMMIT_BRANCH --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text;
          dotnet nuget push "src\Dimerce.MavisClient\bin\Release\*.nupkg" --source $CI_COMMIT_BRANCH;

sast:
  stage: test
  tags:
    - ubuntu
include:
- template: Security/SAST.gitlab-ci.yml
